/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./app/**/*.{js,ts,jsx,tsx}",
        "./pages/**/*.{js,ts,jsx,tsx}",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                light: {
                    black: "#000000",
                    white: "#FFFFFF",
                    greenButton: "#38CB89",
                    mainBg: "#e5e5e5",
                    "charleston-green": "#292D32",
                    gainsboro: "#D8DEE8",
                    flavescent: "#FFEB94",
                    "cadet-grey": "#97A6B7",
                    "lavender-gray": "#BFC8D6",
                    cultured: "#F5F5F6",
                    "lavender-indigo": "#9747FF",
                    "rich-black": "#070A1A",
                    "spanish-gray": "#8F9198",
                    "peach-orange": "#F2CC9D",
                    "carrot-orange": "#E1891C",
                    "philippine-gray": "#948E8E",
                    "light-silver": "#DBD9D9",
                    "ghost-white": "#F9FAFB",
                    "mountain-meadow": "#38CB89",
                    "medium-sea-green": "#30AD74",
                    "charleston-green": "#252735",
                    "go-green": "#0DBF66",
                    "light-red": "#F8CBC9",
                    isabelline: "#F1F0F0",
                    linen: "#FCE9E8",
                    "carrot-orange": "#E1891C",
                    carnelian: "#BF2018",
                    "light-salmon-pink": "#F2A29D",
                    "medium-aquamarine": "#5CD49E",
                    "magic-mint": "#A9E9CC",
                    salem: "#20744E",
                    "chinese-white": "E1E1E1",
                },
                dark: {
                    "charleston-green": "#252735",
                    gainsboro: "#DADADD",
                    " Black Coral": "#5E606A",
                    "spanish-gray": "#8F9198",
                    "peach-orange": "#F2CC9D",
                    "carrot-orange": "#E1891C",
                    "philippine-gray": "#948E8E",
                    "light-silver": "#DBD9D9",
                    "ghost-white": "#F9FAFB",
                    "mountain-meadow": "#38CB89",
                    "go-green": "#0DBF66",
                    "light-red": "#F8CBC9",
                    "charleston-green": "#252735",
                    "dark-gunmetal": "#1F2130",
                    gunmetal: "#2C2F3C",
                    "medium-sea-green": "#30AD74",
                    "black-coffee": "#352929",
                    argent: "#C4C0C0",
                    quartz: "#4A4C58",
                    "eerie-black": "#1E1E1E",
                    "shadow-blue": "#778CA2",
                    "davy-grey": "#54565B",
                },
            },
        },
    },
};
