import Passed from "../components/main/assessment/assessment/viewAssessment/status/passed";
import Inconclusive from "../components/main/assessment/assessment/viewAssessment/status/inconclusive";
import Failed from "../components/main/assessment/assessment/viewAssessment/status/failed";

const viewAssessmentData = [
  {
    name: "Oladeji Damilola",
    applicant_id: "PB-PM-7272",
    program: "Product Manager",
    email: "phoenix@untitledui.com",
    applicant_result: "70",
    status: <Passed />,
  },
  {
    name: "Adeoye Adebimpe",
    applicant_id: "LS-FD-0061",
    program: "Frontend Developer",
    email: "lana@untitledui.com",
    applicant_result: "70",
    status: <Passed />,
  },
  {
    name: "Demi Wilkinson",
    applicant_id: "DW-BD-2519",
    program: "Backend Developer",
    email: "demi@untitledui.com",
    applicant_result: "30",
    status: <Failed />,
  },
  {
    name: "Candice Wu",
    applicant_id: "CW-FD-2375",
    program: "Fullstack Developer",
    email: "candice@untitledui.com",
    applicant_result: "-",
    status: <Inconclusive />,
  },
  {
    name: "Natali Craig",
    applicant_id: "NC-UX-2106",
    program: "UX Designer",
    email: "natali@untitledui.com",
    applicant_result: "90",
    status: <Passed />,
  },
  {
    name: "Drew Cano",
    applicant_id: "DC-UX-0905",
    program: "UX Copywriter",
    email: "drew@untitledui.com",
    applicant_result: "10",
    status: <Failed />,
  },
  {
    name: "Orlando Diggs",
    applicant_id: "OD-UI-7984",
    program: "UI Designer",
    email: "orlando@untitledui.com",
    applicant_result: "50",
    status: <Passed />,
  },
  {
    name: "Andi Lane",
    applicant_id: "AL-PM-3008",
    program: "Product Manager",
    email: "andi@untitledui.com",
    applicant_result: "20",
    status: <Failed />,
  },
  {
    name: "Kate Morrison",
    applicant_id: "KM-QA-8861",
    program: "QA Engineer",
    email: "kate@untitledui.com",
    applicant_result: "50",
    status: <Passed />,
  },
  {
    name: "Kate Morrison",
    applicant_id: "KM-QA-8861",
    program: "QA Engineer",
    email: "kate@untitledui.com",
    applicant_result: "18",
    status: <Failed />,
  },
  {
    name: "Kate Morrison",
    applicant_id: "KM-QA-8861",
    program: "QA Engineer",
    email: "kate@untitledui.com",
    applicant_result: "30",
    status: <Failed />,
  },
  {
    name: "Kate Morrison",
    applicant_id: "KM-QA-8861",
    program: "QA Engineer",
    email: "kate@untitledui.com",
    applicant_result: "-",
    status: <Inconclusive />,
  },
  {
    name: "Kate Morrison",
    applicant_id: "KM-QA-8861",
    program: "QA Engineer",
    email: "kate@untitledui.com",
    applicant_result: "50",
    status: <Passed />,
  },
  {
    name: "Kate Morrison",
    applicant_id: "KM-QA-8861",
    program: "QA Engineer",
    email: "kate@untitledui.com",
    applicant_result: "-",
    status: <Inconclusive />,
  },
  {
    name: "Kate Morrison",
    applicant_id: "KM-QA-8861",
    program: "QA Engineer",
    email: "kate@untitledui.com",
    applicant_result: "10",
    status: <Failed />,
  },
  {
    name: "Kate Morrison",
    applicant_id: "KM-QA-8861",
    program: "QA Engineer",
    email: "kate@untitledui.com",
    applicant_result: "20",
    status: <Failed />,
  },
  {
    name: "Kate Morrison",
    applicant_id: "KM-QA-8861",
    program: "QA Engineer",
    email: "kate@untitledui.com",
    applicant_result: "-",
    status: <Inconclusive />,
  },
  {
    name: "Kate Morrison",
    applicant_id: "KM-QA-8861",
    program: "QA Engineer",
    email: "kate@untitledui.com",
    applicant_result: "50",
    status: <Passed />,
  },
  {
    name: "Kate Morrison",
    applicant_id: "KM-QA-8861",
    program: "QA Engineer",
    email: "kate@untitledui.com",
    applicant_result: "10",
    status: <Failed />,
  },
  {
    name: "Kate Morrison",
    applicant_id: "KM-QA-8861",
    program: "QA Engineer",
    email: "kate@untitledui.com",
    applicant_result: "50",
    status: <Passed />,
  },
];
export default viewAssessmentData;
